# Generated by Django 3.0.2 on 2021-03-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=256)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=256)),
                ('username', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('Admin', 'Admin'), ('Client', 'Client'), ('User', 'User')], default='User', max_length=256)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
